### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by DukeManh** [Andrewnt219/paper-csharp#12]
I'm looking at your project and thinking more tests should be added. 

I'd like to see the coverage to be extended.

I might not write the best `C#` code, but I'll do the best.

**Comment by Andrewnt219** [comment]
@DukeManh There're a lot of missing tests indeed. Some suggestions are `MarkdownParser`, passing help/version, passing 
 directory as an input, passing empty input, specify a different output folder, etc.
